version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5101:5432"
    volumes:
      - cms_showmanagement_postgres_data:/var/lib/postgresql/data

  # https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=docker-hub
  azure-blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports:
      - "5102:10000"
      - "5103:10001"
      - "5104:10002"
    volumes:
      - cms_showmanagement_azure_blob_storage_data:/data

  azure-cli:
    depends_on:
      - azure-blob-storage
    image: mcr.microsoft.com/azure-cli

    command: >
      az storage container create -n show-profile-images --connection-string "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azure-blob-storage:10000/devstoreaccount1;QueueEndpoint=http://azure-blob-storage:10001/devstoreaccount1;"

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    restart: always
    ports:
      - 4317:4317 # OTLP gRPC receiver
    command: --config /etc/otel-collector-config.yaml
    volumes:
      - ./configs/otel-collector-config.yaml:/etc/otel-collector-config.yaml

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./configs/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - prometheus

  loki:
    image: grafana/loki
    ports:
      - 3100:3100

  tempo:
    image: grafana/tempo
    ports:
      - "4333:4317"  # otlp grpc
      - "3200:3200"   # tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./configs/tempo.yaml:/etc/tempo.yaml
      - cms_showmanagement_tempo:/tmp/tempo

volumes:
  cms_showmanagement_postgres_data:
    driver: local
  cms_showmanagement_azure_blob_storage_data:
    driver: local
  cms_showmanagement_tempo:
    driver: local
