apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "1"
data:
  appsettings.json: |
    {
        "Logging": {
            "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetCore": "Warning"
            }
        },
        "ConnectionStrings": {
            "Postgres": {{ .Values.config.connectionStrings.postgres | quote }}
        },
        "Jwt": {
            "Audience": {{ .Values.config.jwt.audience | quote }},
            "Authority": {{ .Values.config.jwt.authority | quote }},
            "RequireHttpsMetadata": {{ .Values.config.jwt.requireHttpsMetadata }}
        },
        "CmsServices": {
            "UserManagement": {
                "BaseAddress": {{ .Values.config.cmsServices.userManagement.baseAddress | quote }},
                "TokenEndpoint": {{ .Values.config.cmsServices.userManagement.tokenEndpoint | quote }},
                "ClientId": {{ .Values.config.cmsServices.userManagement.clientId | quote }},
                "ClientSecret": {{ .Values.config.cmsServices.userManagement.clientSecret | quote }},
                "Audience": {{ .Values.config.cmsServices.userManagement.audience | quote }}
            }
        }
    }