receivers:
  otlp:
    protocols:
      grpc:

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    default_labels_enabled:
      exporter: false
      job: true
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

processors:
  resource:
    attributes:
      - action: insert
        key: service_name
        from_attribute: service.name
      - action: insert
        key: loki.resource.labels
        value: service_name
      - action: insert
        key: TraceId
        from_attribute: traceid

service:
  pipelines:
    logs:
      receivers: [ otlp ]
      processors: [ resource ]
      exporters: [ loki ]
    traces:
      receivers: [otlp]
      exporters: [otlp]